# Copyright 2012-2015 splinter authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

sudo: false
cache: pip
addons:
  firefox: "latest"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - DJANGO_VERSION=1.7.11 DRIVER=tests/test_djangoclient.py
  - DJANGO_VERSION=1.8.7 DRIVER=tests/test_djangoclient.py
  - DJANGO_VERSION=1.9 DRIVER=tests/test_djangoclient.py
  - DJANGO_VERSION=1.8.7 DRIVER=tests/test_flaskclient.py
  - DJANGO_VERSION=1.8.7 DRIVER=tests/test_webdriver_remote.py
  - DJANGO_VERSION=1.8.7 DRIVER=tests/test_webdriver_firefox.py
  - DJANGO_VERSION=1.8.7 DRIVER=tests/test_zopetestbrowser.py
  - DJANGO_VERSION=1.8.7 DRIVER=tests/test_webdriver_phantomjs.py
  - DJANGO_VERSION=1.8.7 DRIVER=tests/test_webdriver_chrome.py
  - DJANGO_VERSION=1.8.7 DRIVER=tests/test_browser.py
  - DJANGO_VERSION=1.8.7 DRIVER=tests/test_element_list.py
  - DJANGO_VERSION=1.8.7 DRIVER=tests/test_request_handler.py
matrix:
  exclude:
    - python: 3.3
      env: DRIVER=tests/test_zopetestbrowser.py
  exclude:
    - python: 3.3
      env: DJANGO_VERSION=1.9
  exclude:
    - python: 3.4
      env: DRIVER=tests/test_zopetestbrowser.py
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 1
  - FILE=`mktemp`; wget "http://chromedriver.storage.googleapis.com/2.20/chromedriver_linux64.zip" -qO $FILE && unzip $FILE chromedriver -d ~; rm $FILE; chmod 777 ~/chromedriver;
  - export PATH=$HOME:$PATH
  - wget http://goo.gl/PJUZfa -O selenium-server.jar
  - java -jar selenium-server.jar > /dev/null 2>&1 &
  - sleep 1
install:
  - pip install -q Django==$DJANGO_VERSION
  - make dependencies
script: ./run_tests.py -w ${DRIVER}
